// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdO4g_jGjP7_TgJhwjQivi1j4_gKhFzQ4',
    appId: '1:486480475076:web:15071e27ab8f3d847bea91',
    messagingSenderId: '486480475076',
    projectId: 'truco-mobile',
    authDomain: 'truco-mobile.firebaseapp.com',
    databaseURL: 'https://truco-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'truco-mobile.appspot.com',
    measurementId: 'G-YXZCKQ89J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbCQoBFiWy9ojhwFVtrjdpYmXqqSD5WM',
    appId: '1:486480475076:android:58e396fc77e3f05d7bea91',
    messagingSenderId: '486480475076',
    projectId: 'truco-mobile',
    databaseURL: 'https://truco-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'truco-mobile.appspot.com',
  );
}
